console.log(getShippingMessage("Australia", 120, 50)); // "Shipping to Australia will cost 170 credits"
console.log(getShippingMessage("Germany", 80, 20)); // "Shipping to Germany will cost 100 credits"
console.log(getShippingMessage("Sweden", 100, 20)); // "Shipping to Sweden will cost 120 credits"
console.log(getShippingMessage("Ukraine", 1000, 500)); // "Shipping to Ukraine will cost 1500 credits"
console.log(getShippingMessage("USA", 2000, 100)); // "Shipping to USA will cost 2100 dits"
console.log(getShippingMessage("Germany", 1500, 200)); // "Shipping to Germacreny will cost 1700 credits"
